---
version: '3'

services:
  dataflow:
    image: dataflow-launch
    build: .
    container_name: dataflow-launch
    ports:
      - 9090:9090
      - 4040:4040
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xmx4g -Xms4g
      - spring.datasource.url=jdbc:mysql://127.0.0.1:3306/dataflow?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
      - spring.datasource.username=root
      - spring.datasource.password=123456
      - logging.level=INFO